version: '3.8'

services:
  backend:
    build: .
    container_name: notebook-backend-test
    user: root
    ports:
      - "8000:8000"
    environment:
      - SQLDB_URL=postgresql+asyncpg://postgres:123456@postgres:5432/air
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: poetry run uvicorn "notebook.main:create_app" --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../frontend  # ใช้ Dockerfile ที่อยู่ใน frontend
    container_name: frontend-test
    ports:
      - "3000:80"  # เปิด port 3000 สำหรับ frontend (React)
    environment:
      - REACT_APP_API_URL=http://backend:8000  # เชื่อมกับ backend ที่ port 8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # เชื่อมโยงโค้ดของ frontend

  postgres:
    image: postgres:16
    container_name: D2-server-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: air
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: D2-PGadmin-test
    environment:
      PGADMIN_DEFAULT_EMAIL: 6410110238@psu.ac.th
      PGADMIN_DEFAULT_PASSWORD: 147896325
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
